{% set version = '0.0-10' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qrng
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qrng_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qrng/qrng_{{ version }}.tar.gz
  sha256: 51ee4eb9bf66fd125db8e5ed750edbc09e41a220994d06c3111f2ae73bcd8648

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('c') }}                # [not win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('qrng')"           # [not win]
    - "\"%R%\" -e \"library('qrng')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qrng
  license: GPL-2.0-only OR GPL-3.0-only
  summary: Functionality for generating (randomized) quasi-random numbers in high dimensions.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: qrng
# Version: 0.0-10
# Encoding: UTF-8
# Title: (Randomized) Quasi-Random Number Generators
# Description: Functionality for generating (randomized) quasi-random numbers in high dimensions.
# Authors@R: c(person(given = "Marius", family = "Hofert", role = c("aut", "cre"), email = "mhofert@hku.hk"), person(given = "Christiane", family = "Lemieux", role = "aut", email = "clemieux@uwaterloo.ca"))
# Author: Marius Hofert [aut, cre], Christiane Lemieux [aut]
# Maintainer: Marius Hofert <mhofert@hku.hk>
# Depends: R (>= 3.0.0)
# Imports: utils
# Suggests: spacefillr, randtoolbox, copula
# Enhances:
# License: GPL-2 | GPL-3
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2024-02-29 14:40:02 UTC
# Packaged: 2024-02-29 14:01:42 UTC; mhofert
